<Type Name="UnhandledExceptionAction" FullName="System.Activities.UnhandledExceptionAction">
  <Metadata><Meta Name="ms.openlocfilehash" Value="eb5bf38c7ceaf3497674d9c7512dd5e4aea25746" /><Meta Name="ms.sourcegitcommit" Value="f435d67b9edfed0109ec78c87b1cbec0b351dc1f" /><Meta Name="ms.translationtype" Value="MT" /><Meta Name="ms.contentlocale" Value="ru-RU" /><Meta Name="ms.lasthandoff" Value="09/24/2019" /><Meta Name="ms.locfileid" Value="71216144" /></Metadata><TypeSignature Language="C#" Value="public enum UnhandledExceptionAction" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi sealed UnhandledExceptionAction extends System.Enum" />
  <TypeSignature Language="DocId" Value="T:System.Activities.UnhandledExceptionAction" />
  <TypeSignature Language="VB.NET" Value="Public Enum UnhandledExceptionAction" />
  <TypeSignature Language="C++ CLI" Value="public enum class UnhandledExceptionAction" />
  <TypeSignature Language="F#" Value="type UnhandledExceptionAction = " />
  <AssemblyInfo>
    <AssemblyName>System.Activities</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Enum</BaseTypeName>
  </Base>
  <Docs>
    <summary><span data-ttu-id="0698c-101">Указывает действие, которое выполняется, когда исключение покидает корневой элемент рабочего процесса.</span><span class="sxs-lookup"><span data-stu-id="0698c-101">Specifies the action that occurs when an exception escapes the root of a workflow.</span></span></summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="0698c-102">Функция <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> вызывается, если исключение покидает корневой элемент рабочего процесса.</span><span class="sxs-lookup"><span data-stu-id="0698c-102">The <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> function is invoked if an exception escapes the root of the workflow.</span></span> <span data-ttu-id="0698c-103">Объект <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> предоставляет доступ к исключению, а также к указателю на объект <xref:System.Activities.Activity>, который сформировал это исключение.</span><span class="sxs-lookup"><span data-stu-id="0698c-103">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> provides access to the exception as well as a pointer to the <xref:System.Activities.Activity> that generated the exception.</span></span> <span data-ttu-id="0698c-104">Параметр Terminate является действием по умолчанию, если не указан обработчик <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>.</span><span class="sxs-lookup"><span data-stu-id="0698c-104">Terminate is the default action if no <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is specified.</span></span>  
  
   
  
## Examples

<span data-ttu-id="0698c-105">В следующем примере кода вызывается рабочий процесс, в котором создается исключение.</span><span class="sxs-lookup"><span data-stu-id="0698c-105">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="0698c-106">Исключение не обрабатывается рабочим процессом, и вызывается обработчик <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>.</span><span class="sxs-lookup"><span data-stu-id="0698c-106">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="0698c-107">Чтобы получить сведения об исключении, проверяются аргументы <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs>, и рабочий процесс завершается.</span><span class="sxs-lookup"><span data-stu-id="0698c-107">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is terminated.</span></span>  
  
[!code-csharp[CFX_WorkflowApplicationExample#6](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#6)]  

<span data-ttu-id="0698c-108">В следующем примере кода вызывается рабочий процесс, в котором создается исключение.</span><span class="sxs-lookup"><span data-stu-id="0698c-108">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="0698c-109">Исключение не обрабатывается рабочим процессом, и вызывается обработчик <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>.</span><span class="sxs-lookup"><span data-stu-id="0698c-109">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="0698c-110">Аргументы <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> проверяются, чтобы получить сведения об исключении, а рабочий процесс завершается.</span><span class="sxs-lookup"><span data-stu-id="0698c-110">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is aborted.</span></span>  
  
[!code-csharp[CFX_WorkflowApplicationExample#7](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#7)]  

<span data-ttu-id="0698c-111">В следующем примере кода вызывается рабочий процесс, в котором создается исключение.</span><span class="sxs-lookup"><span data-stu-id="0698c-111">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="0698c-112">Исключение не обрабатывается рабочим процессом, и вызывается обработчик <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>.</span><span class="sxs-lookup"><span data-stu-id="0698c-112">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="0698c-113">Аргументы <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> проверяются, чтобы получить сведения об исключении, а рабочий процесс отменяется.</span><span class="sxs-lookup"><span data-stu-id="0698c-113">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is cancelled.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#8](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#8)]  

 ]]></format>
    </remarks>
  </Docs>
  <Members>
    <Member MemberName="Abort">
      <MemberSignature Language="C#" Value="Abort" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Activities.UnhandledExceptionAction Abort = int32(0)" />
      <MemberSignature Language="DocId" Value="F:System.Activities.UnhandledExceptionAction.Abort" />
      <MemberSignature Language="VB.NET" Value="Abort" />
      <MemberSignature Language="C++ CLI" Value="Abort" />
      <MemberSignature Language="F#" Value="Abort = 0" Usage="System.Activities.UnhandledExceptionAction.Abort" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Activities</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Activities.UnhandledExceptionAction</ReturnType>
      </ReturnValue>
      <MemberValue>0</MemberValue>
      <Docs>
        <summary><span data-ttu-id="0698c-114">Указывает, что экземпляр <see cref="T:System.Activities.WorkflowApplication" /> должен прервать рабочий процесс.</span><span class="sxs-lookup"><span data-stu-id="0698c-114">Specifies that the <see cref="T:System.Activities.WorkflowApplication" /> should abort the workflow.</span></span> <span data-ttu-id="0698c-115">В результате вызывается делегат, возвращаемый <see cref="P:System.Activities.WorkflowApplication.Aborted" /> после прерывания процесса.</span><span class="sxs-lookup"><span data-stu-id="0698c-115">This results in the calling the delegate returned by the <see cref="P:System.Activities.WorkflowApplication.Aborted" /> bwhen the abort process is complete.</span></span> <span data-ttu-id="0698c-116">Причиной прерывания служит необработанное исключение.</span><span class="sxs-lookup"><span data-stu-id="0698c-116">The unhandled exception is used as the abort reason.</span></span></summary>
      </Docs>
    </Member>
    <Member MemberName="Cancel">
      <MemberSignature Language="C#" Value="Cancel" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Activities.UnhandledExceptionAction Cancel = int32(1)" />
      <MemberSignature Language="DocId" Value="F:System.Activities.UnhandledExceptionAction.Cancel" />
      <MemberSignature Language="VB.NET" Value="Cancel" />
      <MemberSignature Language="C++ CLI" Value="Cancel" />
      <MemberSignature Language="F#" Value="Cancel = 1" Usage="System.Activities.UnhandledExceptionAction.Cancel" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Activities</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Activities.UnhandledExceptionAction</ReturnType>
      </ReturnValue>
      <MemberValue>1</MemberValue>
      <Docs>
        <summary><span data-ttu-id="0698c-117">Указывает, что экземпляр <see cref="T:System.Activities.WorkflowApplication" /> должен запланировать отмену корневого действия и возобновить выполнение.</span><span class="sxs-lookup"><span data-stu-id="0698c-117">Specifies that the <see cref="T:System.Activities.WorkflowApplication" /> should schedule the cancellation of the root activity and resume execution.</span></span> <span data-ttu-id="0698c-118">В результате вызывается делегат, возвращаемый свойством <see cref="P:System.Activities.WorkflowApplication.Completed" /> после отмены процесса.</span><span class="sxs-lookup"><span data-stu-id="0698c-118">This results in a call to the delegate returned by the <see cref="P:System.Activities.WorkflowApplication.Completed" /> property when the cancellation process is complete.</span></span></summary>
      </Docs>
    </Member>
    <Member MemberName="Terminate">
      <MemberSignature Language="C#" Value="Terminate" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Activities.UnhandledExceptionAction Terminate = int32(2)" />
      <MemberSignature Language="DocId" Value="F:System.Activities.UnhandledExceptionAction.Terminate" />
      <MemberSignature Language="VB.NET" Value="Terminate" />
      <MemberSignature Language="C++ CLI" Value="Terminate" />
      <MemberSignature Language="F#" Value="Terminate = 2" Usage="System.Activities.UnhandledExceptionAction.Terminate" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Activities</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Activities.UnhandledExceptionAction</ReturnType>
      </ReturnValue>
      <MemberValue>2</MemberValue>
      <Docs>
        <summary><span data-ttu-id="0698c-119">Указывает, что экземпляр <see cref="T:System.Activities.WorkflowApplication" /> должен запланировать завершение корневого действия и возобновить выполнение.</span><span class="sxs-lookup"><span data-stu-id="0698c-119">Specifies that the <see cref="T:System.Activities.WorkflowApplication" /> should schedule termination of the root activity and resume execution.</span></span> <span data-ttu-id="0698c-120">В результате вызывается делегат, назначаемый свойству <see cref="P:System.Activities.WorkflowApplication.Completed" /> после завершения процесса.</span><span class="sxs-lookup"><span data-stu-id="0698c-120">This results in a call to the delegate assigned to the <see cref="P:System.Activities.WorkflowApplication.Completed" />property when the termination process is complete.</span></span> <span data-ttu-id="0698c-121">Причиной завершения служит необработанное исключение.</span><span class="sxs-lookup"><span data-stu-id="0698c-121">The unhandled exception is used as the termination reason.</span></span> <span data-ttu-id="0698c-122"><see langword="Terminate" /> — действие по умолчанию, если не задан обработчик в свойстве <see cref="P:System.Activities.WorkflowApplication.OnUnhandledException" />.</span><span class="sxs-lookup"><span data-stu-id="0698c-122"><see langword="Terminate" /> is the default action if no <see cref="P:System.Activities.WorkflowApplication.OnUnhandledException" /> handler is specified.</span></span></summary>
      </Docs>
    </Member>
  </Members>
</Type>
